from flask import Flask,request,jsonify,render_template

from openai import OpenAI

from dotenv import load_dotenv

import os
load_dotenv()
app=Flask(__name__)

client =OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

@app.route("/")
def home():
    return render_template("index.html")

@app.route('/analyze',methods=['POST'])
def analyze():
    data=request.json
    resume=data.get('resume')
    
    prompt=f""" You are a professional resume reviewer analyze the resume give 
    1. ATS Score out of 100
    2. Strengths
    3. Weakness
    4. Improvments
    5. Suggested skills
    Resume: {resume}
    """
    
    response=client.chat.completions.create(
        model='gpt-4.1-mini',
        messages=[
            {
                'role':'user',
                "content":prompt
            }
        ]
    )
# the OpenAI API returns a structured response object containing metadata and one or more generated outputs (called choices).

# response → stores the complete API response
# choices → contains a list of generated responses from the model
# [0] → selects the first generated response
# message → accesses the assistant's message object
# content → retrieves the actual textual content generated by the AI
    result=response.choices[0].message.content
    return jsonify({
        'result':result
    })
    
if __name__=="__main__":
    app.run(debug=True)